services:
  - type: web
    name: zillow-fsbo-webhook
    env: node
    buildCommand: npm install
    startCommand: node webhook.js
    envVars:
      - key: SCRAPER_URL
        value: https://zillow-fsbo-scraper.onrender.com
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
        
  - type: web
    name: zillow-fsbo-scraper
    env: node
    buildCommand: npm install
    startCommand: node scraper.js
    envVars:
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"
      - key: ANTICAPTCHA_API_KEY
        sync: false